# Generated by Django 2.2.6 on 2019-10-07 23:22

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thai_choice', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Tom yum goong', 'Tom yum goong'), ('Som tum', 'Som tum'), ('Tom kha kai', 'Tom kha kai'), ('Gaeng daeng', 'Gaeng daeng'), ('Pad thai', 'Pad thai')], max_length=54)),
                ('russian_choice', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Borscht', 'Borscht'), ('Shchi', 'Shchi'), ('Solyanka', 'Solyanka'), ('Ukha', 'Ukha'), ('Pelmeni', 'Pelmeni')], max_length=35)),
                ('french_choice', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Chocolate souffle', 'Chocolate souffle'), ('Beef bourguignon', 'Beef bourguignon'), ('Flamiche', 'Flamiche'), ('Confit de canard', 'Confit de canard'), ('Nicoise salad', 'Nicoise salad')], max_length=74)),
            ],
        ),
    ]
